enable-magisk-update = true
parallel-jobs = 1
compression-level = 9
dpi = "nodpi anydpi 480-640dpi 320-640dpi 320-480dpi 240-480dpi 213-640dpi 160-480dpi 120-640dpi 480dpi 320dpi 240dpi 160dpi"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "latest"
cli-version = "dev"
arch = "arm64-v8a"
riplib = true



[YouTube-Morphe]
app-name = "YouTube"
brand = "Morphe"
build-mode = "both"
version = "21.06.257"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"


[YouTube-Music-Morphe]
app-name = "YouTube Music"
brand = "Morphe"
build-mode = "both"
version = "9.03.52"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"


[Reddit-Morphe]
app-name = "Reddit"
brand = "Morphe"
build-mode = "apk"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
